## INTPUT

video_path: null


## OUTPUT

verbose: False
#verbose: True
save_media: False
# folder path to save the output video
# Path to folder can be absolute or relative to project root
# It should end with a slash
# ES: /home/user/output/
video_output_folder: null
# name of the output video file
# The only format supported for now is mp4
video_output_name: null


## MODEL

model_folder: models/
#model_name: yolov8x.pt
model_name: yolov9e.pt
#model_name: yolo11x.pt
# class_ids of interest
selected_classes: [
  0, # person
  1, # bicycle
  2, # car
  3, # motorcycle
  5, # bus
#  14, # bird
#  15, # cat
#  16, # dog
#  17, # horse
#  18, # sheep
#  19, # cow
#  20, # elephant
#  21, # bear
#  22, # zebra
#  23, # giraffe
]

## OBJECT COUNTER PARAMETERS

# define region points
region_type: vertical_line
#region_points: rectangle
x_distance_from_center: 100
# Euclidean distance from the line from which an object is counted
line_dist_thresh: 40
