## OUTPUT
verbose: True
save_media: False
output_on_file: True

## INPUT
input_type: image
#input_type: video
#media_folder: pna/
#media_folder: bismantova bosco/
media_folder: images/
media_name: 02040042.mp4 # persone + cani

model_name: yolov8x.pt
#model_name: yolo11x.pt
# class_ids of interest
selected_classes: [
  0, # person
  1, # bicycle
  2, # car
  3, # motorcycle
  5, # bus
#  14, # bird
#  15, # cat
#  16, # dog
#  17, # horse
#  18, # sheep
#  19, # cow
#  20, # elephant
#  21, # bear
#  22, # zebra
#  23, # giraffe
]

## OBJECT COUNTER PARAMETERS
# define region points
region_type: vertical_line
#region_points: rectangle
x_distance_from_center: 100
# Euclidean distance from the line from which an object is counted
line_dist_thresh: 40
#cls_txtdisplay_gap: 1000
