verbose: True
#video_name: vehicle-counting.mp4
#video_name: 01270009.mp4 # persone
video_name: 02040042.mp4 # persone + cani
#video_name: 01250003.mp4 # lupo
#video_name: 02250143.mp4 # cane
#video_name: 02180090.mp4 # moto
model_name: yolov8x.pt
# class_ids of interest
selected_classes: [
  0, # person
  1, # bicycle
  2, # car
  3, # motorcycle
  5, # bus
  16, # dog
]

save_video: True

# Object Counter
# define region points
region_type: vertical_line
#region_points: rectangle
x_distance_from_center: 100
# Euclidean distance from the line from which an object is counted
line_dist_thresh: 40
