DATA_FOLDER = 'data/'
# DATA_FOLDER = 'C:\\Users\conci\OneDrive - Università degli Studi di Parma\\UNIPR\DOTTORATO\Bandi\Humanita\Object Counting\\'
MODEL_FOLDER = 'models/'
OUTPUT_FOLDER = 'output/'
CONFIG_PARAMETER_PATH = 'config.yaml'

VIDEO_FORMAT = 'mp4'
# VIDEO_FORMAT = 'avi'
# IMAGE_FORMAT = 'jpg'
IMAGE_FORMAT = 'png'
